services:
  - type: web
    name: easy-paper-backend
    env: python
    region: singapore # or ohio, frankfurt, etc.
    plan: free
    rootDirectory: Easy_Paper/question-paper-generator/server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SCALAR_DOCS
        value: "true"
      - key: ALLOW_ORIGINS
        sync: false # User must update this after deploying frontend
      - key: OPENROUTER_API_KEYS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
